name: imagewidget
description: Fighttech Flutter Image Widget
version: 1.0.2
homepage: https://tech.fighttech.vn

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.0+1
  extended_image: ^7.0.1
  lottie: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1