name: imagewidget
description: Fighttech Flutter Image Widget
version: 1.0.11
homepage: https://github.com/fighttech-vn/image_widget

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.6
  extended_image: ^8.0.1
  lottie: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1